W3 - D3 - quannguyen - class
atruby-team/internship-18-summer pull request #31
Opened 2018-07-06 03:05 UTC by at-quannguyen2

### Người tạo PR kiểm tra những danh sách trước khi đưa cho người review
Task: #27 
- [x] Đã check conventions chưa?
- [x] Bài tập đã hoàn thành chưa
### Người review kiểm tra những danh sách sau trước khi merge
- [x] Đúng conventions chưa?

2018-07-17 07:10 UTC, ghost requested changes

2018-07-17 07:10 UTC, at-nhantruong commented on at-quannguyen/W3/exercise_1.rb
> +
Kết quả bị sai.

2018-07-17 07:10 UTC, at-nhantruong commented on at-quannguyen/W3/exercise_2.rb
> +end
Define method bên trong class Array
Sau đó chạy code như thế này để in ra kết quả `[1,2,3,4].sum # 10`

2018-07-17 07:10 UTC, at-nhantruong commented on at-quannguyen/Week3/ruby.rb
> -  1 => {name: "Paul Barry", areas: ["Programming", "Networking", "Security", "Open Source", "Frameworks"]},
Xoá file này

2018-07-17 07:10 UTC, at-nhantruong commented on at-quannguyen/W3/exercise_4.rb
> +puts StringFormat.format_name 'kaylene _johnson'
Sai kết quả nếu thử với `puts StringFormat.format_name '%kaylene $## 2 @johnson'`

2018-07-20 09:25 UTC, at-nhantruong commented
Fix conflit

2018-07-20 10:12 UTC, at-quannguyen2 commented
Em đã Fix conflict @at-nhantruong  . anh check lại bài giúp em nha

2018-07-28 15:14 UTC, ghost approved these changes

2018-07-28 15:14 UTC, merged